server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/masterdata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root  
    password: root 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: OLX_Masterdata
  zipkin:
    base-url: http://localhost:9411 
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
      